### PR TITLE
Added Secret Agents: Agentic Workflow for Self-Healing Codebase

### PR DESCRIPTION
**Pull request by 0xdesdenova**
A four-part exploration of autonomous memory systems, from schema generation to practical implementation in self-healing code. The series demonstrates how to build sophisticated memory architectures using LangGraph and LLMs, culminating in a production-ready self-healing codebase implementation.

### CODE REVIEW

**Comment by NirDiamant** [comment]
this is an awesome work, but please:
 - submit all code in one notebook. it should be one tutorial encompassing anything inside (and not a project consisting of several files).
 - remove the readme.md file from the PR (I'll correct it afterwords). 
 
thanks!

**Comment by 0xdesdenova** [comment]
Hello Nir.

Of course. What do you think about condensing the memory implementation
into a single file and keeping the self healing code agent separate?

I’ll keep the self healing code agent as the hackathon submission and
prepare the memory tutorial as a separate addition.

Thanks for reaching out.

**Comment by NirDiamant** [comment]
as long as they both relate to the same project please keep it in one self-contained notebook tutorial.
if you think they can be two different tutorials it is also fine :) (but not the same tutorial split into 2 files).
thanks!

**Comment by 0xdesdenova** [comment]
Ok, thanks for the clarification.

**Comment by 0xdesdenova** [comment]
The tutorials have been condensed into a single notebook.

**Comment by NirDiamant** [comment]
amazing, thanks!

**Comment by 0xdesdenova** [comment]
Awesome. Thank you!

**Comment by NirDiamant** [comment]
what is this? [.DS_Store](https://github.com/NirDiamant/GenAI_Agents/blob/main/all_agents_tutorials/.DS_Store)
found it now in the tutorials folder. can i delete it?

**Comment by 0xdesdenova** [comment]
Yes, it can be deleted. It is a Mac OS metadata file specifying special folder attributes. Sorry about that.

**Pull request merged**
