### PR TITLE
Feature/taskifier

### PR DESCRIPTION
**Pull request by mr-fool**
added diagram

### CODE REVIEW

**Comment by NirDiamant** [comment]
hey, saw you opened two PRs for the submission. please make it only one PR, and don't contain the link to the collab notebook in it.

**Comment by mr-fool** [comment]
I will remove the google collab link that's the only change in the new PR

**Comment by NirDiamant** [comment]
It's okay, but you don't need to close the previous one.
but please: the ipynb file should be located straight inside https://github.com/NirDiamant/GenAI_Agents/tree/main/all_agents_tutorials, and not inside another folder called "feature". 
and the data directory the same - use the data directory of the original repo and not under "feature.
thanks!

**Comment by mr-fool** [comment]
Do you want me to fix it? 
When I was searching for the instructions I saw this on CONTRIBUTING.md and posted on discord

> Contributing
> We welcome contributions from the community! If you have a new technique or improvement to suggest:
> 
> Fork the repository
> Create your feature branch: git checkout -b feature/AmazingFeature
> Commit your changes: git commit -m 'Add some AmazingFeature'
> Push to the branch: git push origin feature/AmazingFeature
> Open a pull request

**Comment by NirDiamant** [comment]
the feature is that name of the branch, not the folder :) 
yep. please correct it

**Comment by mr-fool** [comment]
Is it possible if I open a new PR instead coz atm this one is on the feature branch not the main branch

**Comment by NirDiamant** [comment]
yes. then please close this one and you can open a new one

**Comment by mr-fool** [comment]
https://github.com/NirDiamant/GenAI_Agents/pull/24
reopened the old one and it looks like it is working

**Pull request closed without merging**
