### PR TITLE
GenAI Hackathon Submission - Murder Mystery Game with LLM Agents

### PR DESCRIPTION
**Pull request by danigil**

### CODE REVIEW

**Comment by NirDiamant** [comment]
Please make sure that all functions are documented, and thicken a bit the documentation to make it easy for a new reader/user/developer to understand what is going on.
amazing work! 
make this changes and I'll approve the PR :)

**Comment by danigil** [comment]
Hi @NirDiamant 
Thanks for the feedback!

Of course, I'd also like to acknowledge my great teammates and new friends, we made this project together :)
@saurabhlalsaxena (Saurabh) and @zilardo (Lior).

Please see an improved draft below, we'd be happy to hear your thoughts.

https://colab.research.google.com/drive/18kVdYApJ6zrje6yC218rGMcbNSRe8_WZ?usp=sharing

**Comment by NirDiamant** [comment]
this is awesome. 
please commit the new file instead the previous one and I'll approve :)

**Comment by danigil** [comment]
> this is awesome. please commit the new file instead the previous one and I'll approve :)

Done!

**Comment by NirDiamant** [comment]
amazing, thanks!

**Pull request merged**
