### PR TITLE
Taskifier Submission

### PR DESCRIPTION
**Pull request by mr-fool**
Wylliam Cheng and Jason Law

### CODE REVIEW

**Comment by mr-fool** [comment]
reopened it so it should be fine

**Comment by mr-fool** [comment]
@NirDiamant does it work?

**Comment by NirDiamant** [comment]
nope :) 
There should be no father folder (in this case you called it "Taskifier") - it is redundant and creates another hierarchy.
the .ipynb file should be straight here: https://github.com/NirDiamant/GenAI_Agents/tree/main/all_agents_tutorials
and the rest should be in the /data folder of the repo itself (and not under the additional "taskifier" folder).

if you are getting into trouble with this, please ask in the discord channel, many others did it and can assist you with this :)

**Comment by mr-fool** [comment]
asked on discord and reorganize the structure. Hopefully this works

**Pull request merged**
