### PR TITLE
Weather Disaster Management AI Agent

### PR DESCRIPTION
**Pull request by noor92**
## 🌦️ Weather Disaster Management AI Agent
This PR introduces the **Weather Disaster Management AI Agent**, a LangGraph-based intelligent system designed to monitor, analyze, and respond to potential weather-related disasters. It leverages AI models, LangChain workflows, and real-time data integration to provide timely notifications and actionable insights.

- **Purpose**: To enhance disaster preparedness and response by automating alerts and notifications.
- **What has been changed?**  
  - Added a LangGraph workflow to process weather data and trigger notifications.  
  - Integrated AI models for weather pattern analysis and disaster prediction.  
  - Implemented communication tools for real-time email alerts.

### CODE REVIEW

**Comment by noor92** [comment]
Kindly, merge this PR without any error and README.md file as it wasn't resolved on my partner account "asif-ml-developer" .
Please, let me know if any amendment is required .  I really appreciate your patience in this regard.
Thank you so much for your prompt answering and cooperation.
Regards

**Comment by NirDiamant** [comment]
great! 
now on a second view, I see that some changes are needed before merging:
- split the code into more cells. As a tutorial, it should be easier to understand for new people
- add a markdown description above each cell (the new ones you'll add, and the current ones)
- in general, follow the instructions in the CONTRIBUTING.MD file in the repo and re-submit, please. (except for changing the readme)

**Comment by NirDiamant** [comment]
why is there a duplication of the whole code?

**Comment by noor92** [comment]
Hi Nir Diamant,

Thank you for reviewing the work!

The code has been meticulously divided into manageable chunks, with detailed descriptions provided in Markdown format for better clarity and readability.

To elaborate, I’ve developed two distinct agent graphs to address different scenarios:

Real-Data Agent Graph: This graph exclusively processes real-time weather data to ensure reliable and actionable insights.
Hybrid Agent Graph: Designed for testing purposes, this graph operates with both real-time weather data and simulated (dummy) weather states. This allows us to observe the graph's behavior during high-severity weather scenarios without relying solely on real-world events.
This dual approach ensures both operational accuracy and robustness under extreme conditions. I hope this explanation aligns with your expectations and provides the necessary clarity about the implementation.

Looking forward to your feedback!

Best regards,

**Comment by noor92** [comment]
Hi Nir Diamant,

Thank you for reviewing the work!

The code has been meticulously divided into manageable chunks, with
detailed descriptions provided in Markdown format for better clarity and
readability.

To elaborate, I’ve developed two distinct agent graphs to address different
scenarios:

Real-Data Agent Graph: This graph exclusively processes real-time weather
data to ensure reliable and actionable insights.
Hybrid Agent Graph: Designed for testing purposes, this graph operates with
both real-time weather data and simulated (dummy) weather states. This
allows us to observe the graph's behavior during high-severity weather
scenarios without relying solely on real-world events.
This dual approach ensures both operational accuracy and robustness under
extreme conditions. I hope this explanation aligns with your expectations
and provides the necessary clarity about the implementation.

Looking forward to your feedback!

Best regards,

**Comment by NirDiamant** [comment]
I understand, and this is a great idea! Could you make it clearer in the tutorial? At the beginning, describe that there are two parts and explain their purpose. Then, at the start of the second part, include an overview explaining why it’s needed and the specific cases where it will be used. Thanks!

**Comment by noor92** [comment]
As per your instructions, I have incorporated the two distinct scenarios
and provided clear explanations of their purposes. Additionally, I have
included *pictorial diagrams* to illustrate the workflow of graphs for
better visual clarity.

To further enhance understanding, I have also added *step-by-step pictorial
guidance* demonstrating how to execute the second scenario (Hybrid Agent
Graph) and how it operates under various conditions. These visuals aim to
make the tutorial more user-friendly and comprehensible.

I look forward to your feedback and any additional suggestions to improve
the documentation further.

Best regards,

**Comment by NirDiamant** [comment]
very nice! amazing work, and thanks for the corporation on fixing this!

**Comment by noor92** [comment]
Thank you so much for your kind words and for merging our PR! It has been a
pleasure collaborating with you on this project. I truly appreciate your
guidance and support in refining the work, which helped ensure its success.
Looking forward to more opportunities to collaborate and achieve great
results together!

Best regards

**Pull request merged**
