### PR TITLE
Systematic Review of Scientific Articles

### PR DESCRIPTION
**Pull request by bmwise14**
Has the following:
[Systematic Review of Scientific Articles 🏷️](https://github.com/bmwise14/GenAI_Agents/blob/main/all_agents_tutorials/systematic_review_of_scientific_articles.ipynb)

a link to Colab:
https://colab.research.google.com/drive/19IYU2TaBxf3HdqfkBpmbjsmlX0gfsgdE?usp=sharing

A link to Youtube video:
- https://youtu.be/MePOE2m-ACI

Thank you for this opportunity!

### CODE REVIEW

**Comment by NirDiamant** [comment]
Hi Bradley, Could you please remove the readme file from the PR to avoid conflicts. I'll add it afterward. thanks!

**Comment by bmwise14** [comment]
Hi Nir,

Yes, I just removed it  now.

Bradley

**Comment by NirDiamant** [comment]
it doesn't let me merge it (as now it refers to it as deleting the readme file)
then please change it to the current README file from the master, and then I'll be able to merge. thanks!

**Comment by bmwise14** [comment]
Apologies, just added now :)

**Comment by NirDiamant** [comment]
thanks!

**Pull request merged**
