### PR TITLE
Agentcraft Hackathon: Gen AI Career Assistant.

### PR DESCRIPTION
**Pull request by karan3486**
Team : Solo
Gen AI Career assistant Agent

### CODE REVIEW

**Comment by NirDiamant** [comment]
no readme please...
it doesn't let me merge when there is a readme file. either blank or full

**Comment by karan3486** [comment]
Actually I deleted readme.md and agent_output both.
Should I fork again and just push my notebook only or remove readme also?
Sorry for the inconvenience caused. I’m kind of beginner in this.

**Comment by NirDiamant** [comment]
In the PR include only the relevant files. You can open a new one but close
the current one please

**Comment by karan3486** [comment]
closing this PR

**Pull request closed without merging**
