### PR TITLE
Implement Weather Disaster Management AI Agent (Excluding README.md)

### PR DESCRIPTION
**Pull request by asif-ml-developer**
# Implement Weather Disaster Management AI Agent (Excluding README.md)

This pull request introduces the Weather Disaster Management AI Agent, designed to streamline disaster response operations using AI and LangGraph. The following changes are included:

## **Summary of Changes**
1. **Core Features**:
   - Added disaster type detection and response logic.
   - Integrated LangGraph to manage workflows for decision-making and notifications.
2. **Agent Functionality**:
   - Automated email notifications to relevant departments based on disaster types.
   - Enhanced decision-making with Google Gemini LLM integration.
3. **Supporting Files**:
   - Included `all_agents_tutorials/Weather_Disaster_Management_AI_AGENT.ipynb` for notebook-based implementation.
   - Added visual assets in the `images/` folder for system explanation.

## **Special Notes**
- The `README.md` file has been intentionally removed to resolve previous conflicts and will be reintroduced in a future update with detailed documentation.
- The focus of this PR is functionality and not documentation.

## **Testing**
- The agent was tested on simulated scenarios for floods and earthquakes, successfully triggering notifications and executing workflows.
- All implemented features passed initial functionality checks.

## **Next Steps**
- Add support for additional disaster types like wildfires and storms.
- Develop a detailed `README.md` and other documentation to guide users through setup and usage.

### CODE REVIEW

**Comment by NirDiamant** [comment]
it won't let me merge it yet.
I suggest as a workaround to keep the readme md just as the most updated version from the main branch, so there won't be any conflicts, and it will let me merge it. 
thanks!

**Comment by asif-ml-developer** [comment]
can I send through my other github account because here the conflict with
your main README.md file and I am unable to delete your README.md file. Can
I recreate PR from my partner github account, does it work?

**Comment by NirDiamant** [comment]
You can also take the most updated version of README from the master
branch, and then there will be no conflicts

**Comment by asif-ml-developer** [comment]
I try many times from my account to send PR but failed, now I sent it from
my partner github account named noor92

#64 opened in 3 minutes ago by noor92

kindly use it to merge.

Regards

**Comment by asif-ml-developer** [comment]
Dear NirDiamant,

I really appreciate your guidance and cooperation in this regard. Hopefully, you will be able to push to your repository from my partner's account, "noor92", and will like our project. If any amendments are still needed, please inform us, and we will update it according to your instructions.

This is the first hackathon we have ever joined and 1st PR we have ever sent. 

Thank you so much.

Regards,
Asif

**Pull request closed without merging**
